### ISSUE TITLE
23.0.x build tools ? 

### ISSUE THREAD

**Issue by matzew** [appunite/docker#35]
Hi,

the `android-java8` images contain some 23.0.x tools, but not all (e.g. 23.0.2 is missing). Any reason for that ? 

If not, I could PR that ;-)

**Comment by jacek-marchwicki** [comment]
Actually there is a reason. We don't want to make this docker image to become huge. It's already 2GB in size. Usually when we need some additional tools we install them at CI at build time.

We could potentially always add newest build-tools and in time remove old one but this would brake builds of old commits/repositories.

But we are always open for discussion's because always is a better solution.

**Comment by matzew** [comment]
fair enough 👍
