### ISSUE TITLE
Option to have default JDK OracleJDK

### ISSUE THREAD

**Issue by bhavinmdesai** [appunite/docker#43]
The image seems to be using OpenJDK by default.

I am getting following issue:
```
 * What went wrong:
A problem occurred evaluating project ':app'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0
```
I checked my local machine and found that I am using OracleJDK. Can we have something so that the user can have option to switch default JDK ? Or may be can you come up with totally different images ?

Thanks in advance. You're amazing !

**PS: I am using it on my AWS ami.**

**Comment by jacek-marchwicki** [comment]
The issue is probably because: http://stackoverflow.com/a/38503342/1104031

You can always switch docker to older java version (android-java7-r24-4-1) or you can use docker image with java7 and java8 and switch during build:
https://github.com/appunite/docker/tree/master/android-java7-8-r25-0-1 but on newest build tools you need to always use java8 during build process.

But I think the best solution for your issue is described in this stackoverflow answer.
