### ISSUE TITLE
Any plans to update Docker image on Docker Hub?

### ISSUE THREAD

**Issue by panthomakos** [appunite/docker#59]
The latest image on Docker Hub appears to be about 5 months old and contains out of date platform tools. Do you have any plans to push a new image?

**Comment by jacek-marchwicki** [comment]
Hi @panthomakos, I suggest to use *ubuntu-16-04-java7-8* image (https://github.com/appunite/docker/blob/master/ubuntu-16-04-java7-8/README.md).
It's used in our projects and it does not contains any Android SDK, but android gradle plugin (I think since version 2.3) download all dependencies automatically so you can use any SDK that you wish without updating docker image.
If you worry about constantly downloading whole Android SDK you can cache `$ANDROID_HOME` directory between builds as we do.

So actually we don't have plans to update any sdk's only java version that is required to run `./gradlew`

**Comment by panthomakos** [comment]
Thanks for the prompt update! Will investigate the other image.

**Comment by kirtangajjar** [comment]
@jacek-marchwicki Does running `./gradlew` automatically downloads the latest SDK?

I got following error: 
```
SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable
```

**Comment by jacek-marchwicki** [comment]
Hi @kirtangajjar,

Yes, Gradle plugin should download SDK [Google Documentation](https://developer.android.com/studio/intro/update.html#download-with-gradle). This was added in some 2.x version but I don't recall which exactly.

You need to follow instructions described [here](https://github.com/appunite/docker/tree/master/ubuntu-16-04-java7-8):

```bash
export GRADLE_USER_HOME="$(pwd)/.gradle"
export ANDROID_HOME="$(pwd)/.android"
mkdir -p "${ANDROID_HOME}/licenses"
echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e" > "${ANDROID_HOME}/licenses/android-sdk-license"
echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "${ANDROID_HOME}/licenses/android-sdk-preview-license"
echo -e "\nd975f751698a77b662f1254ddbeed3901e976f5a" > "${ANDROID_HOME}/licenses/intel-android-extra-license"
./gradlew --parallel --stacktrace --no-daemon build 
```

Hopefully, This will fix your issue.

**Comment by kirtangajjar** [comment]
@jacek-marchwicki It did. Thank you :)
